Modification 2
Duha22RUS/drf4 pull request #1
Opened 2022-06-08 14:52 UTC by Duha22RUS

2022-06-11 22:31 UTC, ilyachch requested changes

2022-06-11 22:31 UTC, ilyachch commented on amscsait/amscapp/forms.py
> +    def calculate_age(born):
где это используется?

2022-06-11 22:31 UTC, ilyachch commented on amscsait/amscapp/forms.py
> +            text_question_id = field.split("_")[-1]
тут надо выбирать значения, сейчас не обрабатываются TextQuestion

2022-06-11 22:31 UTC, ilyachch commented on amscsait/amscapp/templates/database/add_complaint.html
>      $("#id_question").change(function () {
я бы вообще это все убрал

2022-06-11 22:31 UTC, ilyachch commented on amscsait/amscapp/urls.py
> +from .views import SearchResultsView
лучше это делать через ту же страницу

2022-06-11 22:31 UTC, ilyachch commented on amscsait/amscapp/urls.py
> +    path('sample/', views.sample_view),
зачем?

2022-06-14 10:54 UTC, Duha22RUS reviewed
Вопросы

2022-06-14 10:54 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +                    text_patient_answer=value
Что прописать, для сохранения результатов в виде текста/цифр?

2022-06-14 10:54 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +    def calculate_age(born):
> где это используется?

Это я хотел вывести возраст пациента, чтобы добавить в view_patient.html смотрел в интернете примеры, что берём сегодняшнюю дату и вычитаем дату рождения, то есть patient.date_of_birth, но я не пойму, как мне в html это вывести

2022-06-14 10:54 UTC, Duha22RUS commented on amscsait/amscapp/urls.py
> +from .views import SearchResultsView
> лучше это делать через ту же страницу

Поправил
def get_queryset(request):
    query = request.GET.get('q')
    object_list = Patient.objects.filter(Q(name__icontains=query))
    return render(request, "amscapp/search_result.html", {"object_list": object_list})

2022-06-14 10:54 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +            text_question_id = field.split("_")[-1]
> тут надо выбирать значения, сейчас не обрабатываются TextQuestion

Как это правильно прописать?

2022-06-14 19:24 UTC, ilyachch commented on amscsait/amscapp/forms.py
> +    def calculate_age(born):
это все чудесно, но почему это делается в форме? сделай метод модели, который будет отдавать возраст

2022-06-14 19:26 UTC, ilyachch commented on amscsait/amscapp/urls.py
> +from .views import SearchResultsView
я имею в виду, что надо делать через index page

2022-06-14 19:27 UTC, ilyachch commented on amscsait/amscapp/forms.py
> +            text_question_id = field.split("_")[-1]
ну у тебя названия полей же разное. по нему и определяй

2022-06-15 18:20 UTC, Duha22RUS reviewed
Вопрос

2022-06-15 18:20 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +            self.fields["quest_%s" % quest.id] = forms.CharField(
Я запутался, пытаюсь два дня решить эту проблему, при таком написании кода у меня выводятся вопросы, рядом есть поле  для ввода, но там вводится id

![8](https://user-images.githubusercontent.com/86065188/173896286-caedbb6f-235e-47fb-b0fb-685fb9a1e774.png)

Ну и естественно при сохранении формы возникает ошибка, что вводится текст, и я немного не понимаю, ведь нужно передавать и id, но и ещё и текст ответа, не пойму, как правильно это сделать

![9](https://user-images.githubusercontent.com/86065188/173896540-2c40cc6f-2d2f-4834-bbd1-acc30df723c9.png)

class AnswerForm не поменялся от этого, но на всякий

![6](https://user-images.githubusercontent.com/86065188/173896937-33741ae3-d3c6-46a8-9bfd-1109793d7faa.png)

в def save() так же почти ничего не поменялось, я так же стараюсь передать text_question_id

![7](https://user-images.githubusercontent.com/86065188/173896691-af1eddc2-db57-4e2d-a238-35095eedd7ee.png)

Я пытался прописывать в классе формы код 
`patient_text_answer = list(PatientTextAnswer.objects.all())`

и в def save()
`text_patient_answer=value`

но мне кажется в классе форме нужно что-то ещё прописать, только вот что?)

2022-06-15 20:32 UTC, ilyachch commented on amscsait/amscapp/forms.py
> +            self.fields["quest_%s" % quest.id] = forms.CharField(
я несколько раз писал, что надо завязываться на название поля
```python
def save():
    answers_to_create = []
    text_answers_to_create = []
    for f, v in self.cleaned_data.items():
        if f.starts_with('question_'):
            answers_to_create.append(...)
        elif f.starts_with('quest_'):
            text_answers_to_create.append()
    PatientAnswer.objects.filter(patient=self.instance).delete()
    PatientAnswer.objects.bulk_create(answers_to_create)
    PatientTextAnswer.objects.filter(patient=self.instance).delete()
    PatientTextAnswer.objects.bulk_create(text_answers_to_create)

```

2022-06-16 06:48 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +            self.fields["quest_%s" % quest.id] = forms.CharField(
Я понял.. я пытался всё это в одну модель запихать, передавал из PatientTextAnswer по fk в PatientAnswer.. всё, разобрался, код работает

2022-06-20 07:20 UTC, merged