Design
Duha22RUS/drf4 pull request #5
Opened 2022-06-11 14:11 UTC by Duha22RUS

2022-06-11 22:25 UTC, ilyachch requested changes

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/models.py
> +    text_question = models.CharField("Текст вопроса", max_length=100)
я бы поменял местами слова, как в Question

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/models.py
> +class TextPatientAnswer(models.Model):
и тут - PatientTextAnswer

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/models.py
> +    text_question = models.ForeignKey(to="TextQuestion", on_delete=models.CASCADE)
лучше просто question, чтобы было одинаково с PatientAnswer

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/base.html
> +<html lang="ru" xmlns="http://www.w3.org/1999/html">
это html5 документ, `xmlns="http://www.w3.org/1999/html"` - не нужно

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/base.html
> +  <title>Главная</title>
зря

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/base.html
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anony
после я бы добавил блок extrascript, чтобы можно было дописывать кастомные скрипты

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/index.html
> +      <form action="{% url 'search' %}" method="get">
лучше все это сделать через класс формы и вести не на search, а обратно на index

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/search_result.html
> +        {% for Patient in object_list %}
это переменная, надо с маленькой буквы

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/search_result.html
> +                  <a class="btn btn-default" href="{% url 'make_answers' pk=Patient.pk %}">{% if not answers %}Анкетировать{% else %}
здесь нет answers. я бы добавил в модель пациэнта метод get_answers или свойство answers, которые бы отдавали список ответов или None. тогда тут можно было бы сделать `if patient.answers`

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/view_patient.html
> +  {% if request.user.is_authenticated %}
это лучше рулить через декораторы на view. эта страница вообще не ддожна отдаваться анонимному пользователю

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/view_patient.html
> +    <h2>Анкетирование от: {{ patientanswer.date_of_the_survey }} {{ datesurv }} проведено: {{ user }}</h2>
каждый ответ имеет свою дату. ее лучше выводить отдельно. типа на такой-то вопрос ответ был тогда, а на другой - тогда

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/views.py
> +    datesurv = PatientAnswer.date_of_the_survey
тут просто берется значение поля у класса. работать не будет

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/views.py
>  def view_patient(request, pk):
тут, если надо ограничить права доступа, лучше поставить декоратор

2022-06-11 22:25 UTC, ilyachch commented on amscsait/amscapp/views.py
> -        request, "amscapp/post_form.html", {"form": form, "title": "Изменение пациента"}
получается, все страницы будут называться "главная"?

2022-06-14 09:06 UTC, ilyachch commented
@Duha22RUS 
![image](https://user-images.githubusercontent.com/1570221/173539115-7b77b10e-a1ea-4a5d-b658-a3a1f2695c38.png)
под сообщением можно отвечать. resolve - означает, что пришли к какому-то решению

2022-06-14 10:53 UTC, Duha22RUS reviewed
Вопросы

2022-06-14 10:53 UTC, Duha22RUS commented on amscsait/amscapp/templates/amscapp/view_patient.html
> +    <h2>Анкетирование от: {{ patientanswer.date_of_the_survey }} {{ datesurv }} проведено: {{ user }}</h2>
Как правильно вывести дату создания формы, ведь я прописал в модели date_of_the_survey, но он ничего не выводит)
Пытался через views.py прописать datesurv, но там выводит типо код объекта, но не время создания/редактирования формы
А ещё, как правильно прописать, то, какой пользователь сохранил форму, а то {{ user }} выводит пользователя с которого я захожу, а не того, кто создал/отредактировал эту форму?)

2022-06-14 10:53 UTC, Duha22RUS commented on amscsait/amscapp/templates/amscapp/search_result.html
> +                  <a class="btn btn-default" href="{% url 'make_answers' pk=Patient.pk %}">{% if not answers %}Анкетировать{% else %}
> здесь нет answers. я бы добавил в модель пациэнта метод get_answers или свойство answers, которые бы отдавали список ответов или None. тогда тут можно было бы сделать `if patient.answers`

Да вроде у меня код нормально работает
Когда нет пишется "Анкетировать"
Когда есть уже пишется "Изменить ответы"

2022-06-14 10:53 UTC, Duha22RUS commented on amscsait/amscapp/templates/amscapp/view_patient.html
> +    <h2>Анкетирование от: {{ patientanswer.date_of_the_survey }} {{ datesurv }} проведено: {{ user }}</h2>
> каждый ответ имеет свою дату. ее лучше выводить отдельно. типа на такой-то вопрос ответ был тогда, а на другой - тогда

У нас ведь date_of_survey выводит дату и время когда форма была отправлена в бд, то есть после заполнения вопросов и нажатия кнопки, происходит save.form() и я хотел вывести когда было проведено анкетирование в общем, а не время ответа на каждый вопрос)

2022-06-14 10:53 UTC, Duha22RUS commented on amscsait/amscapp/templates/amscapp/post_form.html
> +        <input class="btn btn-primary btn-block" type="submit" value="{{ submit_text|default:'submit' }}">
Я не совсем пойму, как мне допустим назначить разный текст на кнопки "Регистрация", "Авторизация"
Ну и плюс, например ладно форма регистрации и авторизации..
А если я бы хотел изменить для добавления пациента свой дизайн формы, а тут затрагиваются все формы.. Может как-то прописать условие? я пытался писать что-то типо {% if views.register %} то надпись на кнопке "Регистрация" но это не помогает, может так и не будет работать совсем)
В интернете читал, если только через js script назначить формам id и в зависимости от id формы выдаётся шаблон, но как-то сложно, просто не охота создавать другой шаблон html

2022-06-14 19:14 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/view_patient.html
> +    <h2>Анкетирование от: {{ patientanswer.date_of_the_survey }} {{ datesurv }} проведено: {{ user }}</h2>
1) я описал это тут: https://github.com/Duha22RUS/drf4/pull/5/files#r895073618
2) чтобы показывалось, какой пользователь заполнял - надо это сохранять и хранить где-то

2022-06-14 19:15 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/view_patient.html
> +    <h2>Анкетирование от: {{ patientanswer.date_of_the_survey }} {{ datesurv }} проведено: {{ user }}</h2>
нигде ничего не выводится, потому, что date_of_survey не берется

2022-06-14 19:18 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/search_result.html
> +                  <a class="btn btn-default" href="{% url 'make_answers' pk=Patient.pk %}">{% if not answers %}Анкетировать{% else %}
а откуда оно берется? ListView отдает только object_list, в котором только пациенты

2022-06-14 19:21 UTC, ilyachch commented on amscsait/amscapp/templates/amscapp/post_form.html
> +        <input class="btn btn-primary btn-block" type="submit" value="{{ submit_text|default:'submit' }}">
можно передавать значение из view в параметре `submit_text`:
```
    return render(
        request,
        "amscapp/post_form.html",
        {"form": form, "submit_text": "Регистрация"},
    )
```

2022-06-17 17:43 UTC, Duha22RUS reviewed
Если я хочу вывести например первые 10 вопросов, как это правильно прописать?
![drf – answer_form html 2022-06-17 01 39 28](https://user-images.githubusercontent.com/86065188/174350627-cf744697-8ff2-43ba-87d0-507daf80ca2a.png)

2022-06-19 16:58 UTC, Duha22RUS reviewed
Сортировка

2022-06-19 16:58 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +        #     self.fields[f'{question.id}-{question.type_.value}-{text_questions.id}-{text_questions.answer}'] = sorted(
В модели я добавил int поля

![1](https://user-images.githubusercontent.com/86065188/174491914-25fb6dfd-443f-4b37-8e8f-f05e9d7ac274.png)

![2](https://user-images.githubusercontent.com/86065188/174491924-7ce42dbd-fd38-4700-8d71-8ca3b7cd45f6.png)

Получается для сортировки же не нужен id?
Достаточно ведь номер вопроса и тип вопроса?

```
for question in sorted(*questions, **questions_text):
            self.fields[f'{question.question_number}-{question.type_.value}']
```

Или как правильно прописать сортировку? У меня ещё и название полей одинаковое у двух моделей

2022-06-19 21:26 UTC, ilyachch commented on amscsait/amscapp/forms.py
> +        #     self.fields[f'{question.id}-{question.type_.value}-{text_questions.id}-{text_questions.answer}'] = sorted(
почему `**`? в sorted можно передавать лямбду сортировки

2022-06-20 05:25 UTC, Duha22RUS commented on amscsait/amscapp/forms.py
> +        #     self.fields[f'{question.id}-{question.type_.value}-{text_questions.id}-{text_questions.answer}'] = sorted(
> почему `**`? в sorted можно передавать лямбду сортировки номер тебе не нужен в полях

А ну просто здесь так было, я так и прописал))

![3](https://user-images.githubusercontent.com/86065188/174530860-23a1507d-7414-4845-8d39-f5d212dcf333.png)

2022-06-20 07:21 UTC, merged